#!/bin/bash

# useless stuff

echo "                                    "
echo "                                    "
echo "█████╗█████╗█████╗█████╗█████╗█████╗"
echo "╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝"
echo "                                    "
echo "                                    "
echo "                                    "
echo "    ██████╗ ██╗   ██╗███╗   ██╗     "
echo "    ██╔══██╗╚██╗ ██╔╝████╗  ██║     "
echo "    ██║  ██║ ╚████╔╝ ██╔██╗ ██║     "
echo "    ██║  ██║  ╚██╔╝  ██║╚██╗██║     "
echo "    ██████╔╝   ██║   ██║ ╚████║     "
echo "    ╚═════╝    ╚═╝   ╚═╝  ╚═══╝     "
echo "                                    "
echo "    ██████╗  █████╗ ██████╗         "
echo "    ██╔══██╗██╔══██╗██╔══██╗        "
echo "    ██████╔╝███████║██████╔╝        "
echo "    ██╔═══╝ ██╔══██║██╔══██╗        "
echo "    ██║     ██║  ██║██║  ██║        "
echo "    ╚═╝     ╚═╝  ╚═╝╚═╝  ╚═╝        "
echo "                                    "
echo "     ██████╗ ███████╗██╗            "
echo "    ██╔════╝ ██╔════╝██║            "
echo "    ██║  ███╗███████╗██║            "
echo "    ██║   ██║╚════██║██║            "
echo "    ╚██████╔╝███████║██║            "
echo "     ╚═════╝ ╚══════╝╚═╝            "
echo "                                    "
echo "                                    "
echo "                                    "
echo "█████╗█████╗█████╗█████╗█████╗█████╗"
echo "╚════╝╚════╝╚════╝╚════╝╚════╝╚════╝"
echo "                                    "
echo "                                    "

#   make /storage/dynpargsi/images folder

echo "Twrp flashable zip generator from gsi images for dynamic partition devices"
echo ""
echo "version 1"
echo ""
echo "creating input directory.."
echo ""
mkdir -p ~/storage/shared/dynpargsi/input
echo "input directory created at /storage/dynpargsi/images"
echo "please place the images there"
echo ""
echo "done"
